#pragma once

#include <cstdint>
#include <unordered_map>

namespace Instruments
{
	constexpr int kInstrumentsCount = 128;

	enum class InstrumentType : std::uint8_t
	{
		AcousticGrandPiano,
		BrightAcousticPiano,
		ElectricGrandPiano,
		HonkyTonkPiano,
		RhodesPiano,
		ChorusedPiano,
		Harpsichord,
		Clavinet,
		Celesta,
		Glockenspiel,
		MusicBox,
		Vibraphone,
		Marimba,
		Xylophone,
		TubularBells,
		Dulcimer,
		HammondOrgan,
		PercussiveOrgan,
		RockOrgan,
		ChurchOrgan,
		ReedOrgan,
		Accordion,
		Harmonica,
		TangoAccordion,
		AcousticGuitarNylon,
		AcousticGuitarSteel,
		ElectricGuitarJazz,
		ElectricGuitarClean,
		ElectricGuitarMuted,
		OverdrivenGuitar,
		DistortionGuitar,
		GuitarHarmonics,
		AcousticBass,
		ElectricBassFinger,
		ElectricBassPick,
		FretlessBass,
		SlapBass1,
		SlapBass2,
		SynthBass1,
		SynthBass2,
		Violin,
		Viola,
		Cello,
		Contrabass,
		TremoloStrings,
		PizzicatoStrings,
		OrchestralHarp,
		Timpani,
		StringEnsemble1,
		StringEnsemble2,
		SynthStrings1,
		SynthStrings2,
		ChoirAahs,
		VoiceOohs,
		SynthVoice,
		OrchestraHit,
		Trumpet,
		Trombone,
		Tuba,
		MutedTrumpet,
		FrenchHorn,
		BrassSection,
		SynthBrass1,
		SynthBrass2,
		SopranoSax,
		AltoSax,
		TenorSax,
		BaritoneSax,
		Oboe,
		EnglishHorn,
		Bassoon,
		Clarinet,
		Piccolo,
		Flute,
		Recorder,
		PanFlute,
		BottleBlow,
		Shakuhachi,
		Whistle,
		Ocarina,
		Lead1Square,
		Lead2Sawtooth,
		Lead3CalliopeLead,
		Lead4ChifferLead,
		Lead5Charang,
		Lead6Voice,
		Lead7Fifths,
		Lead8BrassLead,
		Pad1NewAge,
		Pad2Warm,
		Pad3Polysynth,
		Pad4Choir,
		Pad5Bowed,
		Pad6Metallic,
		Pad7Halo,
		Pad8Sweep,
		FX1Rain,
		FX2Soundtrack,
		FX3Crystal,
		FX4Atmosphere,
		FX5Brightness,
		FX6Goblins,
		FX7Echoes,
		FX8SciFi,
		Sitar,
		Banjo,
		Shamisen,
		Koto,
		Kalimba,
		Bagpipe,
		Fiddle,
		Shana,
		TinkleBell,
		Agogo,
		SteelDrums,
		Woodblock,
		TaikoDrum,
		MelodicTom,
		SynthDrum,
		ReverseCymbal,
		GuitarFretNoise,
		BreathNoise,
		Seashore,
		BirdTweet,
		TelephoneRing,
		Helicopter,
		Applause,
		Gunshot,
		Default
	};

	inline static const std::unordered_map<std::string, InstrumentType> kStringToInstrument =
	{
		{"AcousticGrandPiano", InstrumentType::AcousticGrandPiano},
		{"BrightAcousticPiano", InstrumentType::BrightAcousticPiano},
		{"ElectricGrandPiano", InstrumentType::ElectricGrandPiano},
		{"Honky-tonkPiano", InstrumentType::HonkyTonkPiano},
		{"RhodesPiano", InstrumentType::RhodesPiano},
		{"ChorusedPiano", InstrumentType::ChorusedPiano},
		{"Harpsichord", InstrumentType::Harpsichord},
		{"Clavinet", InstrumentType::Clavinet},
		{"Celesta", InstrumentType::Celesta},
		{"Glockenspiel", InstrumentType::Glockenspiel},
		{"Music box", InstrumentType::MusicBox},
		{"Vibraphone", InstrumentType::Vibraphone},
		{"Marimba", InstrumentType::Marimba},
		{"Xylophone", InstrumentType::Xylophone},
		{"TubularBells", InstrumentType::TubularBells},
		{"Dulcimer", InstrumentType::Dulcimer},
		{"HammondOrgan", InstrumentType::HammondOrgan},
		{"PercussiveOrgan", InstrumentType::PercussiveOrgan},
		{"RockOrgan", InstrumentType::RockOrgan},
		{"ChurchOrgan", InstrumentType::ChurchOrgan},
		{"ReedOrgan", InstrumentType::ReedOrgan},
		{"Accordion", InstrumentType::Accordion},
		{"Harmonica", InstrumentType::Harmonica},
		{"TangoAccordion", InstrumentType::TangoAccordion},
		{"AcousticGuitarNylon", InstrumentType::AcousticGuitarNylon},
		{"AcousticGuitarSteel", InstrumentType::AcousticGuitarSteel},
		{"ElectricGuitarJazz", InstrumentType::ElectricGuitarJazz},
		{"ElectricGuitarClean", InstrumentType::ElectricGuitarClean},
		{"ElectricGuitarMuted", InstrumentType::ElectricGuitarMuted},
		{"OverdrivenGuitar", InstrumentType::OverdrivenGuitar},
		{"DistortionGuitar", InstrumentType::DistortionGuitar},
		{"Guitar Harmonics", InstrumentType::GuitarHarmonics},
		{"AcousticBass", InstrumentType::AcousticBass},
		{"ElectricBassFinger", InstrumentType::ElectricBassFinger},
		{"ElectricBassPick", InstrumentType::ElectricBassPick},
		{"FretlessBass", InstrumentType::FretlessBass},
		{"SlapBass1", InstrumentType::SlapBass1},
		{"SlapBass2", InstrumentType::SlapBass2},
		{"SynthBass1", InstrumentType::SynthBass1},
		{"SynthBass2", InstrumentType::SynthBass2},
		{"Violin", InstrumentType::Violin},
		{"Viola", InstrumentType::Viola},
		{"Cello", InstrumentType::Cello},
		{"Contrabass", InstrumentType::Contrabass},
		{"TremoloStrings", InstrumentType::TremoloStrings},
		{"PizzicatoStrings", InstrumentType::PizzicatoStrings},
		{"OrchestralHarp", InstrumentType::OrchestralHarp},
		{"Timpani", InstrumentType::Timpani},
		{"StringEnsemble1", InstrumentType::StringEnsemble1},
		{"StringEnsemble2", InstrumentType::StringEnsemble2},
		{"SynthStrings1", InstrumentType::SynthStrings1},
		{"SynthStrings2", InstrumentType::SynthStrings2},
		{"ChoirAahs", InstrumentType::ChoirAahs},
		{"VoiceOohs", InstrumentType::VoiceOohs},
		{"SynthVoice", InstrumentType::SynthVoice},
		{"OrchestraHit", InstrumentType::OrchestraHit},
		{"Trumpet", InstrumentType::Trumpet},
		{"Trombone", InstrumentType::Trombone},
		{"Tuba", InstrumentType::Tuba},
		{"MutedTrumpet", InstrumentType::MutedTrumpet},
		{"FrenchHorn", InstrumentType::FrenchHorn},
		{"BrassSection", InstrumentType::BrassSection},
		{"SynthBrass1", InstrumentType::SynthBrass1},
		{"SynthBrass2", InstrumentType::SynthBrass2},
		{"SopranoSax", InstrumentType::SopranoSax},
		{"AltoSax", InstrumentType::AltoSax},
		{"TenorSax", InstrumentType::TenorSax},
		{"BaritoneSax", InstrumentType::BaritoneSax},
		{"Oboe", InstrumentType::Oboe},
		{"EnglishHorn", InstrumentType::EnglishHorn},
		{"Bassoon", InstrumentType::Bassoon},
		{"Clarinet", InstrumentType::Clarinet},
		{"Piccolo", InstrumentType::Piccolo},
		{"Flute", InstrumentType::Flute},
		{"Recorder", InstrumentType::Recorder},
		{"PanFlute", InstrumentType::PanFlute},
		{"BottleBlow", InstrumentType::BottleBlow},
		{"Shakuhachi", InstrumentType::Shakuhachi},
		{"Whistle", InstrumentType::Whistle},
		{"Ocarina", InstrumentType::Ocarina},
		{"Lead1Square", InstrumentType::Lead1Square},
		{"Lead2Sawtooth", InstrumentType::Lead2Sawtooth},
		{"Lead3CalliopeLead", InstrumentType::Lead3CalliopeLead},
		{"Lead4ChifferLead", InstrumentType::Lead4ChifferLead},
		{"Lead5Charang", InstrumentType::Lead5Charang},
		{"Lead6Voice", InstrumentType::Lead6Voice},
		{"Lead7Fifths", InstrumentType::Lead7Fifths},
		{"Lead8BrassLead", InstrumentType::Lead8BrassLead},
		{"Pad1NewAge", InstrumentType::Pad1NewAge},
		{"Pad2Warm", InstrumentType::Pad2Warm},
		{"Pad3Polysynth", InstrumentType::Pad3Polysynth},
		{"Pad4Choir", InstrumentType::Pad4Choir},
		{"Pad5Bowed", InstrumentType::Pad5Bowed},
		{"Pad6Metallic", InstrumentType::Pad6Metallic},
		{"Pad7Halo", InstrumentType::Pad7Halo},
		{"Pad8Sweep", InstrumentType::Pad8Sweep},
		{"FX1Rain", InstrumentType::FX1Rain},
		{"FX2Soundtrack", InstrumentType::FX2Soundtrack},
		{"FX3Crystal", InstrumentType::FX3Crystal},
		{"FX4Atmosphere", InstrumentType::FX4Atmosphere},
		{"FX5Brightness", InstrumentType::FX5Brightness},
		{"FX6Goblins", InstrumentType::FX6Goblins},
		{"FX7Echoes", InstrumentType::FX7Echoes},
		{"FX8Sci-fi", InstrumentType::FX8SciFi},
		{"Sitar", InstrumentType::Sitar},
		{"Banjo", InstrumentType::Banjo},
		{"Shamisen", InstrumentType::Shamisen},
		{"Koto", InstrumentType::Koto},
		{"Kalimba", InstrumentType::Kalimba},
		{"Bagpipe", InstrumentType::Bagpipe},
		{"Fiddle", InstrumentType::Fiddle},
		{"Shana", InstrumentType::Shana},
		{"TinkleBell", InstrumentType::TinkleBell},
		{"Agogo", InstrumentType::Agogo},
		{"SteelDrums", InstrumentType::SteelDrums},
		{"Woodblock", InstrumentType::Woodblock},
		{"TaikoDrum", InstrumentType::TaikoDrum},
		{"MelodicTom", InstrumentType::MelodicTom},
		{"SynthDrum", InstrumentType::SynthDrum},
		{"ReverseCymbal", InstrumentType::ReverseCymbal},
		{"GuitarFretNoise", InstrumentType::GuitarFretNoise},
		{"BreathNoise", InstrumentType::BreathNoise},
		{"Seashore", InstrumentType::Seashore},
		{"BirdTweet", InstrumentType::BirdTweet},
		{"TelephoneRing", InstrumentType::TelephoneRing},
		{"Helicopter", InstrumentType::Helicopter},
		{"Applause", InstrumentType::Applause},
		{"Gunshot", InstrumentType::Gunshot}
	};

	inline static const std::unordered_map<InstrumentType, std::uint8_t> kInstrumentToLabel =
	{
		{InstrumentType::AcousticGrandPiano, 0},
		{InstrumentType::BrightAcousticPiano, 1},
		{InstrumentType::ElectricGrandPiano, 2},
		{InstrumentType::HonkyTonkPiano, 3},
		{InstrumentType::RhodesPiano, 4},
		{InstrumentType::ChorusedPiano, 5},
		{InstrumentType::Harpsichord, 6},
		{InstrumentType::Clavinet, 7},
		{InstrumentType::Celesta, 8},
		{InstrumentType::Glockenspiel, 9},
		{InstrumentType::MusicBox, 10},
		{InstrumentType::Vibraphone, 11},
		{InstrumentType::Marimba, 12},
		{InstrumentType::Xylophone, 13},
		{InstrumentType::TubularBells, 14},
		{InstrumentType::Dulcimer, 15},
		{InstrumentType::HammondOrgan, 16},
		{InstrumentType::PercussiveOrgan, 17},
		{InstrumentType::RockOrgan, 18},
		{InstrumentType::ChurchOrgan, 19},
		{InstrumentType::ReedOrgan, 20},
		{InstrumentType::Accordion, 21},
		{InstrumentType::Harmonica, 22},
		{InstrumentType::TangoAccordion, 23},
		{InstrumentType::AcousticGuitarNylon, 24},
		{InstrumentType::AcousticGuitarSteel, 25},
		{InstrumentType::ElectricGuitarJazz, 26},
		{InstrumentType::ElectricGuitarClean, 27},
		{InstrumentType::ElectricGuitarMuted, 28},
		{InstrumentType::OverdrivenGuitar, 29},
		{InstrumentType::DistortionGuitar, 30},
		{InstrumentType::GuitarHarmonics, 31},
		{InstrumentType::AcousticBass, 32},
		{InstrumentType::ElectricBassFinger, 33},
		{InstrumentType::ElectricBassPick, 34},
		{InstrumentType::FretlessBass, 35},
		{InstrumentType::SlapBass1, 36},
		{InstrumentType::SlapBass2, 37},
		{InstrumentType::SynthBass1, 38},
		{InstrumentType::SynthBass2, 39},
		{InstrumentType::Violin, 40},
		{InstrumentType::Viola, 41},
		{InstrumentType::Cello, 42},
		{InstrumentType::Contrabass, 43},
		{InstrumentType::TremoloStrings, 44},
		{InstrumentType::PizzicatoStrings, 45},
		{InstrumentType::OrchestralHarp, 46},
		{InstrumentType::Timpani, 47},
		{InstrumentType::StringEnsemble1, 48},
		{InstrumentType::StringEnsemble2, 49},
		{InstrumentType::SynthStrings1, 50},
		{InstrumentType::SynthStrings2, 51},
		{InstrumentType::ChoirAahs, 52},
		{InstrumentType::VoiceOohs, 53},
		{InstrumentType::SynthVoice, 54},
		{InstrumentType::OrchestraHit, 55},
		{InstrumentType::Trumpet, 56},
		{InstrumentType::Trombone, 57},
		{InstrumentType::Tuba, 58},
		{InstrumentType::MutedTrumpet, 59},
		{InstrumentType::FrenchHorn, 60},
		{InstrumentType::BrassSection, 61},
		{InstrumentType::SynthBrass1, 62},
		{InstrumentType::SynthBrass2, 63},
		{InstrumentType::SopranoSax, 64},
		{InstrumentType::AltoSax, 65},
		{InstrumentType::TenorSax, 66},
		{InstrumentType::BaritoneSax, 67},
		{InstrumentType::Oboe, 68},
		{InstrumentType::EnglishHorn, 69},
		{InstrumentType::Bassoon, 70},
		{InstrumentType::Clarinet, 71},
		{InstrumentType::Piccolo, 72},
		{InstrumentType::Flute, 73},
		{InstrumentType::Recorder, 74},
		{InstrumentType::PanFlute, 75},
		{InstrumentType::BottleBlow, 76},
		{InstrumentType::Shakuhachi, 77},
		{InstrumentType::Whistle, 78},
		{InstrumentType::Ocarina, 79},
		{InstrumentType::Lead1Square, 80},
		{InstrumentType::Lead2Sawtooth, 81},
		{InstrumentType::Lead3CalliopeLead, 82},
		{InstrumentType::Lead4ChifferLead, 83},
		{InstrumentType::Lead5Charang, 84},
		{InstrumentType::Lead6Voice, 85},
		{InstrumentType::Lead7Fifths, 86},
		{InstrumentType::Lead8BrassLead, 87},
		{InstrumentType::Pad1NewAge, 88},
		{InstrumentType::Pad2Warm, 89},
		{InstrumentType::Pad3Polysynth, 90},
		{InstrumentType::Pad4Choir, 91},
		{InstrumentType::Pad5Bowed, 92},
		{InstrumentType::Pad6Metallic, 93},
		{InstrumentType::Pad7Halo, 94},
		{InstrumentType::Pad8Sweep, 95},
		{InstrumentType::FX1Rain, 96},
		{InstrumentType::FX2Soundtrack, 97},
		{InstrumentType::FX3Crystal, 98},
		{InstrumentType::FX4Atmosphere, 99},
		{InstrumentType::FX5Brightness, 100},
		{InstrumentType::FX6Goblins, 101},
		{InstrumentType::FX7Echoes, 102},
		{InstrumentType::FX8SciFi, 103},
		{InstrumentType::Sitar, 104},
		{InstrumentType::Banjo, 105},
		{InstrumentType::Shamisen, 106},
		{InstrumentType::Koto, 107},
		{InstrumentType::Kalimba, 108},
		{InstrumentType::Bagpipe, 109},
		{InstrumentType::Fiddle, 110},
		{InstrumentType::Shana, 111},
		{InstrumentType::TinkleBell, 112},
		{InstrumentType::Agogo, 113},
		{InstrumentType::SteelDrums, 114},
		{InstrumentType::Woodblock, 115},
		{InstrumentType::TaikoDrum, 116},
		{InstrumentType::MelodicTom, 117},
		{InstrumentType::SynthDrum, 118},
		{InstrumentType::ReverseCymbal, 119},
		{InstrumentType::GuitarFretNoise, 120},
		{InstrumentType::BreathNoise, 121},
		{InstrumentType::Seashore, 122},
		{InstrumentType::BirdTweet, 123},
		{InstrumentType::TelephoneRing, 124},
		{InstrumentType::Helicopter, 125},
		{InstrumentType::Applause, 126},
		{InstrumentType::Gunshot, 127}
	};
}